// inquirer package for prompts, fs for file writing, import generateMarkdown for the file text
const inquirer = require('inquirer')
const fs = require('fs');
const generateMarkdown = require('./utils/generateMarkdown');

// create an array of questions for user input
const questions = ['What is your project title?', 'Provide a description of your application and the project as a whole.', 'How would you instruct someone to install this application?', 'How would a user use your application?', 'What are your contribution guidelines?', 'What tests did you run for your application? How can a user run those same tests?', 'What is your GitHub username?', 'What is your email?', 'What license would you like to use?'];
const [titleQ, descriptionQ, installQ, usageQ, contributionQ, testsQ, gitHubQ, emailQ, licenseQ] = questions

// writes a markdown file with text generated by generateMarkdown and information given by the user
function writeToFile(fileName, data) {
    fs.writeFile(fileName, generateMarkdown(data), (err) =>
        err ? console.error(err) : console.log('File created!'))
}

// function to start app with prompts that will be used to generate markdown text
function init() {
    inquirer
        .prompt([
            {
                type: 'input',
                message: titleQ,
                name: 'title'
            },
            {
                type: 'input',
                message: descriptionQ,
                name: 'description'
            },
            {
                type: 'input',
                message: installQ,
                name: 'install'
            },
            {
                type: 'input',
                message: usageQ,
                name: 'usage'
            },
            {
                type: 'input',
                message: contributionQ,
                name: 'contribution'
            },
            {
                type: 'input',
                message: testsQ,
                name: 'tests'
            },
            {
                type: 'input',
                message: gitHubQ,
                name: 'github'
            },
            {
                type: 'input',
                message: emailQ,
                name: 'email'
            },
            {
                type: 'list',
                message: licenseQ,
                choices: ['MIT', 'GPL v2', 'Apache', 'None'],
                name: 'license'
            },
        ])
        .then((response) => writeToFile('my-README.md', response))
}

// Function call to initialize app
init();
